Repository BHAVANA1497/GatorDesk, pull requests merged in 2022-04, with the labels that each got.

#95 added service files to admin-lost-found-component
  frontend/gator-desk/src/app/admin-lost-and-found/admin-lost-and-found.component.spec.ts
  frontend/gator-desk/src/app/admin-lost-and-found/admin-lost-and-found.component.ts
  frontend/gator-desk/src/app/admin-lost-and-found/admin-lost-and-found.service.spec.ts
  frontend/gator-desk/src/app/admin-lost-and-found/admin-lost-and-found.service.ts
  frontend/gator-desk/src/app/app-routing.module.ts
  frontend/gator-desk/src/app/app.module.ts
Labels: backend

#120 Componenttesting
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.html
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.spec.ts
Labels: frontend

#158 Componenttesting
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.html
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.ts
  frontend/gator-desk/src/app/admin-lost-and-found/admin-lost-and-found.component.css
  frontend/gator-desk/src/app/admin-lost-and-found/admin-lost-and-found.component.html
  frontend/gator-desk/src/app/admin-lost-and-found/admin-lost-and-found.component.ts
  frontend/gator-desk/src/app/admin-lost-and-found/admin-lost-and-found.service.ts
  frontend/gator-desk/src/app/announcement/announcement.component.html
  frontend/gator-desk/src/app/announcement/announcement.component.ts
  frontend/gator-desk/src/app/announcement/announcement.service.ts
  frontend/gator-desk/src/app/app-routing.module.ts
  frontend/gator-desk/src/app/app.component.css
  frontend/gator-desk/src/app/app.component.html
  frontend/gator-desk/src/app/app.module.ts
  frontend/gator-desk/src/app/home/home.component.html
  frontend/gator-desk/src/app/home/home.component.ts
  frontend/gator-desk/src/app/lost-and-found/lost-and-found.component.html
  frontend/gator-desk/src/app/lost-and-found/lost-and-found.component.ts
  frontend/gator-desk/src/app/lost-and-found/lost-and-found.service.ts
  frontend/gator-desk/src/app/providers/authentication.service.spec.ts
  frontend/gator-desk/src/app/providers/authentication.service.ts
  frontend/gator-desk/src/app/shared/admin-header-nav/admin-header-nav.component.css
  frontend/gator-desk/src/app/shared/admin-header-nav/admin-header-nav.component.html
  frontend/gator-desk/src/app/shared/admin-header-nav/admin-header-nav.component.spec.ts
  frontend/gator-desk/src/app/shared/admin-header-nav/admin-header-nav.component.ts
  frontend/gator-desk/src/app/shared/header-nav/header-nav.component.html
  frontend/gator-desk/src/app/shared/header-nav/header-nav.component.ts
Labels: completed

#161 modified lost and found component
  backend/webapp/model/user.go
  backend/webapp/views/announcement-handler.go
  frontend/gator-desk/src/app/admin-announcemet/admin-annoucement.service.ts
  frontend/gator-desk/src/app/admin-lost-and-found/admin-lost-and-found.component.html
  frontend/gator-desk/src/app/app-routing.module.ts
  frontend/gator-desk/src/app/login/login.component.ts
  frontend/gator-desk/src/app/lost-and-found/lost-and-found.component.css
  frontend/gator-desk/src/app/lost-and-found/lost-and-found.component.html
  frontend/gator-desk/src/app/lost-and-found/lost-and-found.component.ts
  frontend/gator-desk/src/app/lost-and-found/lost-and-found.service.ts
  frontend/gator-desk/src/app/providers/authentication.service.ts
  frontend/gator-desk/src/app/signup/signup.component.html
Labels: completed

#170 integrated link feature with backend
  frontend/gator-desk/src/app/admin-lost-and-found/admin-lost-and-found.component.ts
  frontend/gator-desk/src/app/admin-lost-and-found/admin-lost-and-found.service.ts
  frontend/gator-desk/src/app/app-routing.module.ts
  frontend/gator-desk/src/app/app.module.ts
  frontend/gator-desk/src/app/home/home.component.ts
  frontend/gator-desk/src/app/lost-and-found/lost-and-found.component.css
  frontend/gator-desk/src/app/lost-and-found/lost-and-found.component.html
  frontend/gator-desk/src/app/lost-and-found/lost-and-found.component.ts
  frontend/gator-desk/src/app/lost-and-found/lost-and-found.service.ts
Labels: completed

#175 TestPostFoundItemFailCase Added
  backend/webapp/found_test.go
Labels: completed

#177 TestListFoundItemsPassCase
  backend/webapp/found_test.go
Labels: unit-testing

#179 List All Found Items Fail Case Scenario
  backend/webapp/found_test.go
Labels: backend

#181 List Found Items by User Pass Scenario
  backend/webapp/found_test.go
Labels: backend, unit-testing

#183 TestListFoundItemsByUserFailCase
  backend/webapp/found_test.go
Labels: backend
