Repository BHAVANA1497/GatorDesk, pull requests merged in 2022-03, with the labels that each got.

#45 added login component
  frontend/gator-desk/package-lock.json
  frontend/gator-desk/package.json
  frontend/gator-desk/src/app/admin-announcemet/admin-annoucemet.admin.ts
  frontend/gator-desk/src/app/admin-announcemet/admin-announcemet.component.html
  frontend/gator-desk/src/app/admin-announcemet/admin-announcemet.component.ts
  frontend/gator-desk/src/app/app.module.ts
  frontend/gator-desk/src/app/login/login.component.css
  frontend/gator-desk/src/app/login/login.component.html
  frontend/gator-desk/src/app/login/login.component.spec.ts
  frontend/gator-desk/src/app/login/login.component.ts
  frontend/gator-desk/src/app/providers/common.service.spec.ts
  frontend/gator-desk/src/app/providers/common.service.ts
  frontend/gator-desk/src/app/providers/user.service.spec.ts
  frontend/gator-desk/src/app/providers/user.service.ts
Labels: completed

#46 initialized cypress in project
  frontend/gator-desk/angular.json
  frontend/gator-desk/cypress.json
  frontend/gator-desk/cypress/fixtures/example.json
  frontend/gator-desk/cypress/integration/spec.ts
  frontend/gator-desk/cypress/plugins/index.ts
  frontend/gator-desk/cypress/support/commands.ts
  frontend/gator-desk/cypress/support/index.ts
  frontend/gator-desk/cypress/tsconfig.json
  frontend/gator-desk/package-lock.json
  frontend/gator-desk/package.json
Labels: completed

#49 Announcement service backend integration
  frontend/gator-desk/src/app/announcement/announcement.component.html
  frontend/gator-desk/src/app/announcement/announcement.component.ts
  frontend/gator-desk/src/app/announcement/announcement.service.ts
  frontend/gator-desk/src/app/app.module.ts
Labels: completed

#51 Integration
  backend/webapp/main.db
  backend/webapp/model/announcement.go
  frontend/gator-desk/cypress/integration/home.test.js
  frontend/gator-desk/cypress/integration/spec.ts
  frontend/gator-desk/package-lock.json
  frontend/gator-desk/package.json
  frontend/gator-desk/src/app/admin-announcemet/admin-annoucement.service.ts
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.css
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.html
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.spec.ts
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.ts
  frontend/gator-desk/src/app/announcement/annoucement.service.ts
  frontend/gator-desk/src/app/announcement/announcement.component.html
  frontend/gator-desk/src/app/announcement/announcement.component.ts
  frontend/gator-desk/src/app/app-routing.module.ts
  frontend/gator-desk/src/app/app.module.ts
  frontend/gator-desk/src/app/login/login.component.html
  frontend/gator-desk/src/app/shared/header-nav/header-nav.component.html
Labels: bug

#53 Added Cypress testcases
  frontend/gator-desk/cypress/integration/home.test.js
  frontend/gator-desk/src/app/app.component.spec.ts
  frontend/gator-desk/test/announcement.test.js
Labels: completed

#59 added jest ui test cases
  frontend/gator-desk/cypress/integration/home.test.js
  frontend/gator-desk/package-lock.json
  frontend/gator-desk/package.json
  frontend/gator-desk/src/app/admin-announcemet/admin-annoucement.service.ts
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.spec.ts
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.ts
  frontend/gator-desk/src/app/login/login.component.spec.ts
  frontend/gator-desk/src/app/shared/header-nav/header-nav.component.html
Labels: completed

#60 added test cases for jest annoucement component
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.spec.ts
  frontend/gator-desk/src/app/announcement/announcement.component.spec.ts
Labels: completed

#63 modified test cases
  frontend/gator-desk/src/app/admin-announcemet/admin-announcement.component.spec.ts
Labels: bug

#69 Added Sprint3.md file
  Sprint3.md
Labels: documentation
